### ISSUE TITLE
unable to recognize "dapr-config.yaml": no matches for kind "Configuration" in version "dapr.io/v1alpha1"

### ISSUE THREAD

**Issue by stephdep** [EdwinVW/dapr-traffic-control#17]
Hi Edwin,
Thanks for this great sample. 
For me everything works fine when running selfhosted, however when I want to deploy to K8s
using the start.ps1, I see the following messages : 

unable to recognize "dapr-config.yaml": no matches for kind "Configuration" in version "dapr.io/v1alpha1"
unable to recognize "pubsub-rabbitmq.yaml": no matches for kind "Component" in version "dapr.io/v1alpha1"
unable to recognize "state-redis.yaml": no matches for kind "Component" in version "dapr.io/v1alpha1"
unable to recognize "email.yaml": no matches for kind "Component" in version "dapr.io/v1alpha1"
unable to recognize "entrycam.yaml": no matches for kind "Component" in version "dapr.io/v1alpha1"
unable to recognize "exitcam.yaml": no matches for kind "Component" in version "dapr.io/v1alpha1"

The pods and all other stuff gets deployed to k8s, only no dapr components.

I have the following dapr version 
CLI version: 1.5.0
Runtime version: 1.5.0
Windows machine running docker desktop 

Any ideas ?  Thanks !

**Comment by stephdep** [comment]
Arrrrg
Found out that dapr wasn't installed yet on the cluster.
running the following in a command window did the trick. Maybe a reminder in the doc would be helpfull.

dapr init -k --runtime-version 1.5.0

**Comment by EdwinVW** [comment]
Hi @stephdep. Thanks for your interest in this sample app. 
And what happened to you has happened to me also ... multiple times :) . So don't worry about it!
I will add a note to the documentation to make this a bit clearer.

**Comment by EdwinVW** [comment]
I've added a troubleshooting section for running on Kubernetes (see 46b3629).

**Comment by stephdep** [comment]
Excellent @EdwinVW, thanks for continuously improving the sample(s).
