### ISSUE TITLE
vehicle changing lanes between enter and exit

### ISSUE THREAD

**Issue by crystalgreen** [EdwinVW/dapr-traffic-control#19]
This issue is not relevant for the demonstration of dapr concepts, it's just a business logic issue.
When a vehicle changes the lane between the first and the second cam, the actor falsely believes there is a lost vehicle. This may never happen in a simulation but in the real world.
See [this code](https://github.com/EdwinVW/dapr-traffic-control/blob/main/src/TrafficControlService/Actors/VehicleActor.cs#L90).
Also, vehicles that change lanes will never be fined if they are too fast.

Maybe you could mention this in a code comment for others who stumble upon this. Or you find a solution to correctly handle this case for a more realistic implementation.

**Comment by EdwinVW** [comment]
Hi @crystalgreen. Thanks for your interest in the sample app!

The calculation of the average speed and the detection of lost vehicles is independent of the lane in which the car enters and exists. The lane is purely used for informational logging and making the sample somewhat more realistic. 

The `roadId` used in the code is the Id of the entire highway by the way. This could be used to change the behavior per specific highway. But this is currently not used in the sample.

**Comment by crystalgreen** [comment]
Thanks for your quick response. It seems I haven't looked deep enough into the app to understand this correctly. 
Sorry for my hasty remark. BTW: your sample app is a great way to study dapr!

**Comment by EdwinVW** [comment]
No problem @crystalgreen. Nice to hear that the sample app is helping you to learn Dapr!
