### ISSUE TITLE
State not correctly updated in the Actor exemple

### ISSUE THREAD

**Issue by srollinet** [EdwinVW/dapr-traffic-control#20]
Hi!

I am new to Dapr and I was checking your Actor example, to compare it with Orleans.

There is probably a small mistake when you update the state. As you create a new instance of `VehicleState`, I think you have to replace the state with this new instance.

https://github.com/EdwinVW/dapr-traffic-control/blob/491facbe599302e7180baba8fc31a1f19fc32b1f/src/TrafficControlService/Actors/VehicleActor.cs#L50-L53

**Comment by EdwinVW** [comment]
Hi @srollinet. Thanks for your interest in this sample application!

I was able to reproduce your issue. Indeed, the `ExitTimeStamp` property stays `null` in the stored `VehicleState` instance after `RegisterExitAsync` has completed. I'll push a fix shortly.
