### ISSUE TITLE
TrafficControlService exits 

### ISSUE THREAD

**Issue by thinkgandhi** [EdwinVW/dapr-traffic-control#23]
**Describe the bug**
When I run TrafficControlService using powershell or command line , the service exits.

**To Reproduce**
1. Just run all the service one by one

**Expected behavior**
When I run TrafficControlService using powershell or command line , the service exits.

**Screenshots**
 
![image](https://user-images.githubusercontent.com/3099639/175766248-aade7904-1ccb-47b9-9b84-24311a88e5f4.png)

**Environment (please share as much info as possible):**
 - Windows 11
 - Software versions

**Comment by EdwinVW** [comment]
Hi @thinkgandhi. Thanks for your interest in the Dapr sample app!

The error implies that no connection could be made with the MQTT broker running on port 1883. Did you start all the necessary infrastructure parts before starting the services as [described  in the readme](https://github.com/edwinvw/dapr-traffic-control#run-the-application-in-dapr-self-hosted-mode)?

**Comment by thinkgandhi** [comment]
Sorry for my late response. It worked.  I missed the step running infrastructure setup.
