### ISSUE TITLE
WebSocket connection Fails in Visual Simulation

### ISSUE THREAD

**Issue by adrobson** [EdwinVW/dapr-traffic-control#31]
**Describe the bug**
I receive the following error message:
mqttws31.min.js:36 WebSocket connection to 'ws://127.0.0.1:9001/mqtt' failed: 
This results in nothing (green screen) been shown in the Visual Simulation and the above error in the Browser Console

**To Reproduce**
1. Install
2. Open cmd prompt
3. Switch to VisualSimulation project
4. Dotnet run
5. browse to localhost:5000

**Expected behavior**
The visual simulation should run

**Screenshots**

**Environment (please share as much info as possible):**
 - Windows 11
 - Docker 4.17.1 , 
- Running locally
- Chrome latest and Edge latest

**Additional context**
I've never run Mosquitto before and may not have run anything using Websockets before.

**Comment by EdwinVW** [comment]
Hi @adrobson.

I was not able to reproduce your issue. Everything worked as expected when following [the instructions](https://github.com/EdwinVW/dapr-traffic-control#run-the-application-in-dapr-self-hosted-mode).

Some questions to troubleshoot:
1. What version of the Dapr CLI and Runtime are running? Use dapr version to check:
![image](https://github.com/EdwinVW/dapr-traffic-control/assets/1908205/2fa8842d-0edc-4333-af4c-2add0b0abcd1)
2. Have you started all the infrastructure components? Use `docker ps` to check whether Mosquitto is running correctly:
![image](https://github.com/EdwinVW/dapr-traffic-control/assets/1908205/d5a60c09-652e-4bf7-b999-3b6c80093b91)
3. Have you started all the services with Dapr. Use `dapr list` to check:
![image](https://github.com/EdwinVW/dapr-traffic-control/assets/1908205/aae6a3b8-da24-4c5c-9e76-faa02ab074cf)

**Comment by EdwinVW** [comment]
Hi @adrobson.

Any update on this issue?
