### ISSUE TITLE
I have some problems deploying your code

### ISSUE THREAD

**Issue by rojamajor** [EdwinVW/dapr-traffic-control#9]
os:mac 11.4
docker:3.4.0
minikube:v1.21.0
kubectl version ：
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.7", GitCommit:"132a687512d7fb058d0f5890f07d4121b3f0a2e2", GitTreeState:"clean", BuildDate:"2021-05-12T12:32:49Z", GoVersion:"go1.15.12", Compiler:"gc", Platform:"linux/amd64"}

Exec lifecycle hook ([/daprd --wait]) for Container "daprd" in Pod "finecollectionservice-7d966fc9b-bs8dk_dapr-trafficcontrol(56b568ca-672e-4f46-aa24-0f21c6fce0ec)" failed - error: command '/daprd --wait' exited with 137: , message: ""
Back-off restarting failed container

![image](https://user-images.githubusercontent.com/25579539/123760609-9c8beb00-d8f3-11eb-8c02-a240debe2620.png)

thanks

**Comment by EdwinVW** [comment]
I haven't been able to reproduce this issue. So I need more info to try and figure this out. 

I have some questions for you:

1. How do you start the solution? Do you use the start.ps1 script in the /src/k8s folder?
2. Have you tried to rebuild the Docker images?
3. Have you tried running everything in self-hosted mode and did that work (see the [documentation](https://github.com/EdwinVW/dapr-traffic-control#run-the-application-in-dapr-self-hosted-mode))?
4. Are you sure the other services run with a Dapr sidecar? You can check the number of containers in the pod. This should be 2.
5. Can you share any additional logging from the failing sidecar container?

**Comment by rojamajor** [comment]
Yes, I used the start.ps1 script, and I also rebuild docker images，but I did not try to run in self-hosted mode，Look at my screenshot, everything else is fine but Finecollectionservice does not work.

![image](https://user-images.githubusercontent.com/25579539/123797870-3914b400-d919-11eb-97ea-8fd4709c64b6.png)


![image](https://user-images.githubusercontent.com/25579539/123797722-0ff42380-d919-11eb-9ee4-958fcae6e837.png)

**Comment by EdwinVW** [comment]
Thanks for the update.

1. Do you have any memory restrictions imposed on Docker? It could be caused by lack of available memory for starting the container.
2. And are you running a VPN of some sort?

**Comment by EdwinVW** [comment]
Hi @zhonghaochen. Any updates on this issue?
